on: [workflow_dispatch]

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    name: Try using a matrix strategy
    strategy:
      matrix:
        pkg: [core, editor, i18n]
        include:
          - pkg: app
            flags: '--testPathPattern=".tsx"'
          - pkg: app
            flags: '--testPathPattern=".ts"'
    steps:
      - name: Show output per pkg
        run: echo "yarn ${{matrix.pkg}} test ${{matrix.flags}}"
