on: [workflow_dispatch]

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    name: Try using a matrix strategy
    strategy:
      matrix:
        pkg: [core, editor, i18n]
        include:
          - pkg: app
            flags: '--testPathPattern=".tsx" --shard=1/2'
            option: .tsx
          - pkg: app
            flags: '--testPathPattern=".tsx" --shard=2/2'
            option: .tsx
          - pkg: app
            flags: '--testPathPattern=".ts"'
            option: .ts
    steps:
      - name: Show output ${{matrix.pkg}}${{matrix.option}}
        run: echo "yarn ${{matrix.pkg}} test ${{matrix.flags}}"
